# Generated by Django 3.2.7 on 2021-09-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/500x500.png?text=Default', upload_to='blog\\images'),
        ),
    ]
